# Matriks

## Pengertian matriks

Matriks adalah **sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung**.

Tanda kurung yang biasa digunakan adalah "`()`" atau "`[]`". Matriks diberi nama dengan huruf kapital, seperti $A$, $B$, $C$, dan lain sebagainya.

Contoh:

$A=\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{matrix} 
\right]$

$B=\left(
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{matrix} 
\right)$

$C=\left[
\begin{matrix}
0 & 1 & 0 & 0 & 0 \\
4 & 2 & 2 & 0 & 0 \\ 
2 & 4 & 2 & 0 & 0 \\ 
1 & 1 & 2 & 0 & 0 \\ 
0 & 0 & 1 & 2 & 1
\end{matrix} 
\right]$

Latihan Soal
1. l1
1. l2
1. l3
1. l4
1. l5

**Tugas**

Ketentuan:
- Buatlah suatu tabel dengan baris berisi minimal 3 teman kalian, dan kolom berisikan karakteristik mereka yang dapat dituliskan secara numerik


- Nyatakan tabel tersebut dalam bentuk matriks, beri nama matriksnya
- Kumpulkan minggu depan dalam selembar kertas

## Ordo matriks

Ukuran pada matriks disebut dengan **ordo**.

Dinotasikan dalam bentuk:
> $A_{m\times n}$ disebut $A$ berukuran (berordo) $m\times n$

dimana $m$ adalah banyak **baris** dan $n$ adalah banyak **kolom**.


Contoh:

Jika
$A=
\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{matrix} 
\right]$
maka $A_{3\times 3}$
dengan ordonya $3\times 3$

Jika
$B=
\left[
\begin{matrix}
1 & 2 \\
3 & 4 \\ 
5 & 6 
\end{matrix} 
\right]$
maka $B_{3\times 2}$ 
dengan ordonya $3\times 2$

Jika
$C=\left[
\begin{matrix}
0 & 1 & 0 & 0 & 0 \\
4 & 2 & 2 & 0 & 0 \\ 
2 & 4 & 2 & 0 & 0 \\ 
1 & 1 & 2 & 0 & 0 \\ 
0 & 0 & 1 & 2 & 1
\end{matrix} 
\right]$
maka $C_{5\times 5}$ 
dengan ordonya $5\times 5$

Jika
$D=
\left[
\begin{matrix}
1 & 2 & 3 & 4
\end{matrix} 
\right]$
maka $D_{1\times 4}$ 
dengan ordonya $1\times 4$

Latihan Soal
1. Buat matriks bebas dengan ukuran $3\times 2$
1. Buat matriks bebas dengan ordo $4\times 1$
1. Tulis notasi dan tentukan Ordo dari matriks berikut:\
   a. $A=\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{matrix} 
\right]$

   b. $B=\left[
\begin{matrix}
1 & 2 & 3 & 10 & 11 \\
4 & 5 & 6 & 12 & 13 \\ 
7 & 8 & 9 & 14 & 15 
\end{matrix} 
\right]$

   c. $C=\left[
\begin{matrix}
1 & 2 & 3 & 10 & 11 & 14\\
4 & 5 & 6 & 12 & 13 & 15
\end{matrix} 
\right]$

   d. $K=\left[
\begin{matrix}
a \\
b \\
c \\
d \\ 
e
\end{matrix} 
\right]$

   e. $L=\left[
\begin{matrix}
1 & 2 & 3 & 4
\end{matrix} 
\right]$

   f. $M=\left[
\begin{matrix}
1 & a\\
b & 5\\ 
4 & c\\ 
d & 8
\end{matrix} 
\right]$
1. Buat matriks nol dengan ukuran $3$
1. Buat matriks diagonal dengan ukuran $4$

## Elemen matriks

Bilangan yang terdapat di dalam matriks disebut **elemen matriks**.

Dinotasikan dengan huruf non-kapital yang diberi indeks seperti ini:
>$a_{ij}$ disebut anggota matriks $A$ pada **baris ke `i`** dan **kolom ke `j`** 

Contoh:

$A=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right]$

$a_{21}$ menyatakan elemen matriks $A$ pada baris ke-`2` kolom ke-`1`.\
$a_{32}$ menyatakan elemen matriks $A$ pada baris ke-`3` kolom ke-`2`.

$B=
\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{matrix} 
\right]$

$b_{21}$ menyatakan elemen matriks $B$ pada baris ke-`2` kolom ke-`1`, yaitu 4.\
$b_{13}$ menyatakan elemen matriks $B$ pada baris ke-`1` kolom ke-`3`, yaitu 3.

Latihan Soal
1. $A=\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{matrix} 
\right]$, Tentukan $a_{32}$ dan $a_{12}$

1. $B=\left[
\begin{matrix}
1 & 2 & 3 & 10 & 11 \\
4 & 5 & 6 & 12 & 13 \\ 
7 & 8 & 9 & 14 & 15 
\end{matrix} 
\right]$, Tentukan $b_{35}$,  $b_{24}$, dan $b_{12}$

1. $C=\left[
\begin{matrix}
1 & 2 & 3 & 10 & 11 & 14\\
4 & 5 & 6 & 12 & 13 & 15
\end{matrix} 
\right]$, Tentukan $c_{25}$,  $c_{14}$, dan $c_{22}$

1. $K=\left[
\begin{matrix}
a \\
b \\
c \\
d \\ 
e
\end{matrix} 
\right]$, Tentukan $k_{31}$dan $k_{11}$

1. $L=\left[
\begin{matrix}
1 & 2 & 3 & 4
\end{matrix} 
\right]$, Tentukan $l_{11}$ dan $l_{13}$

1. $M=\left[
\begin{matrix}
1 & a\\
b & 5\\ 
4 & c\\ 
d & 8
\end{matrix} 
\right]$, Tentukan $m_{32}$,  $m_{22}$, dan $m_{41}$

## Jenis-jenis Matriks

1. Matriks baris\
   Matriks baris adalah matriks yang hanya memiliki **1 buah baris saja**. Matriks baris memiliki ordo $1\times n$.
    >$A_{1\times 3}=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13}
\end{matrix} 
\right]$ 

1. Matriks kolom\
   Matriks kolom adalah matriks yang hanya memiliki **1 buah kolom saja**. Matriks kolom memiliki ordo $n\times 1$.
    >$A_{3\times 1}=
\left[
\begin{matrix}
a_{11} \\
a_{21} \\ 
a_{31}
\end{matrix} 
\right]$

1. Matriks persegi\
   Matriks persegi adalah matriks yang **banyak barisnya sama dengan banyak kolomnya**. Matriks persegi memiliki ordo $n\times n$.
    >$A_{3\times 3}=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right]$
   
   Elemen matriks $A$ yang posisi baris dan kolomnya sama disebut sebagai **diagonal utama**.

1. Matriks diagonal\
   Matriks diagonal adalah matriks persegi yang elemen **selain diagonal utamanya bernilai nol**. Matriks diagonal memiliki ordo $n\times n$.
    >$A_{3\times 3}=
\left[
\begin{matrix}
a_{11} & 0 & 0 \\
0 & a_{22} & 0 \\ 
0 & 0 & a_{33} 
\end{matrix} 
\right]$

1. Matriks segitiga atas\
   Matriks segitiga atas adalah matriks persegi yang elemen **di bawah diagonal utamanya bernilai nol**. Matriks segitiga atas memiliki ordo $n\times n$.
    >$A_{3\times 3}=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
0 & a_{22} & a_{23} \\ 
0 & 0 & a_{33} 
\end{matrix} 
\right]$

1. Matriks segitiga bawah\
   Matriks segitiga bawah adalah matriks persegi yang elemen **di atas diagonal utamanya bernilai nol**. Matriks segitiga bawah memiliki ordo $n\times n$.
    >$A_{3\times 3}=
\left[
\begin{matrix}
a_{11} & 0 & 0 \\
a_{21} & a_{22} & 0 \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right]$

1. Matriks identitas\
   Matriks identitas adalah matriks persegi yang **diagonal utamanya bernilai 1, selainnya bernilai nol**. Matriks identitas memiliki ordo $n\times n$. Penamaan matriks identitas menggunakan huruf kapital $I$, indeksnya menyatakan ordo/ukuran matriks identitas.
   >$I_3=
\left[
\begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\ 
0 & 0 & 1 
\end{matrix} 
\right]$

1. Matriks nol\
   Matriks nol adalah matriks yang **seluruh elemennya bernilai nol**. Matriks nol memiliki ordo $m\times n$ *(bebas)*.
    >$O_{3\times 3}=
\left[
\begin{matrix}
0 & 0 & 0 \\
0 & 0 & 0 \\ 
0 & 0 & 0
\end{matrix} 
\right]$

## Transpose Matriks

Transpose matriks adalah suatu matriks yang didapatkan setelah **menukar kolom dengan baris** (dan sebaliknya) suatu elemen matriks. Suatu elemen  matriks $A$ yaitu $a_{ij}$ diubah menjadi $a_{ji}$.

Misal

$A=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right]$

Transpose dari matriks $A$ dinotasikan:
> $A'$ atau $A^t$ atau $A^T = \left[
\begin{matrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{32} \\ 
a_{13} & a_{23} & a_{33} 
\end{matrix} 
\right]$

Ordo dari transpose matriks kebalikan dari matriks awalnya, misal $A_{3\times 2}$ maka $A^T_{2\times 3}$

In [1]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A=\n', A)
print('A^T=\n', A.T)

A=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A^T=
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Contoh: \
Tentukan transpose dan ordo dari matriks berikut:
1. $B=
\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix} 
\right]$, ordonya $3\times 3$

    maka $B^T=
\left[
\begin{matrix}
1 & 4 & 7 \\
2 & 5 & 8 \\ 
3 & 6 & 9
\end{matrix} 
\right]$, ordonya $3\times 3$

2. $C=
\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{matrix} 
\right]$, ordonya $2\times 3$

    maka $C^T=
\left[
\begin{matrix}
1 & 4 \\
2 & 5 \\ 
3 & 6
\end{matrix} 
\right]$, ordonya $3\times 2$

3. $K=
\left[
\begin{matrix}
a & b & c & d & e & f 
\end{matrix} 
\right]$, ordonya $1\times 6$

    maka $K^T=
\left[
\begin{matrix}
a \\
b \\ 
c \\
d \\
e \\ 
f
\end{matrix} 
\right]$, ordonya $6\times 1$

## Kesamaan Matriks

Suatu matriks dikatakan sama dengan matriks lainnya jika memenuhi berikut:
1. **Ordonya** sama
1. **Elemen seletak** nilainya sama

Contoh :
1. $A=
\left[
\begin{matrix}
1 & b & 3 \\
c & 5 & d \\ 
7 & e & 9
\end{matrix} 
\right]$ \
$B=
\left[
\begin{matrix}
j & 2 & 3 \\
4 & k & 6 \\ 
7 & 8 & l
\end{matrix} 
\right]$ \
Jika $A=B$ maka : \
$\left[
\begin{matrix}
1 & a & 3 \\
b & 5 & c \\ 
7 & d & 9
\end{matrix} 
\right] =
\left[
\begin{matrix}
j & 2 & 3 \\
4 & k & 6 \\ 
7 & 8 & l
\end{matrix} 
\right]$ \
Sehingga : \
$a=2, b=3, c=5, d=7, j=1, k=5, l=9$

1. $A=
\left[
\begin{matrix}
1 & 2x-1 \\
3y+2 & 6
\end{matrix} 
\right]$ \
$B=
\left[
\begin{matrix}
1 & 3\\
-4 & x-2y
\end{matrix} 
\right]$ \
Jika $A=B$ maka : \
$\left[
\begin{matrix}
1 & 2x-1 \\
3y+2 & 6
\end{matrix} 
\right] =
\left[
\begin{matrix}
1 & 3\\
-4 & x-2y
\end{matrix} 
\right]$ \
Sehingga : \
$2x-1=3$ \
$2x=3+1$ \
$2x=4$ \
$\implies x=2$ \
$3y+2=-4$ \
$3y=-4-2$ \
$3y=-6$ \
$\implies y=-2$ \
Coba cek : $x-2y=2-2(-2)=2+4=6$

Latihan soal:

3. $A=
\left[
\begin{matrix}
2 & x+y \\
x-y & 1
\end{matrix} 
\right]$ \
$B=
\left[
\begin{matrix}
2 & 7 \\
3 & 1
\end{matrix} 
\right]$ \
Jika $A=B$ maka tentukan x dan y!
3. $A=
\left[
\begin{matrix}
2x+3y & 2x \\
3y & 4
\end{matrix} 
\right]$ \
$B=
\left[
\begin{matrix}
-5 & -9 \\
4 & 4
\end{matrix} 
\right]$ \
Jika $A=B^T$ maka tentukan x dan y!
3. $A=
\left[
\begin{matrix}
a+b & c \\
0 & -b
\end{matrix} 
\right]$ \
Jika $A^T=I_2$ maka tentukan a, b dan c!

**Tugazz..** \
Diberikan suatu matriks $A,B$ yang memenuhi kesamaan di bawah ini: \
$A=
\left[
\begin{matrix}
-3 & m+\frac{3}{5} & x\\
c & z & x-y\\
2 & \frac{k}{3} & 3
\end{matrix} 
\right]$, 
$B=
\left[
\begin{matrix}
x+y & \frac{2}{3}l & a+b\\
y & 2k & 4\\
x & 5 & a^2
\end{matrix} 
\right]$ \
$A+I=B^T$ \
Tentukan nilai $a,b,x,y,z,k,l,m$ dimana nilai $c$ bebas dan setiap orang berbeda

## Operasi Matriks

### Operasi penjumlahan dan pengurangan

Suatu matriks bisa dijumlahkan atau dikurangkan dengan matriks lainnya jika **ordonya sama**. Cara pengoperasiannya yaitu dengan **menjumlahkan atau mengurangi elemen yang seletak**.

Operasi penjumlahan dinotasikan sebagai berikut :
> $A_{m\times n}+B_{m\times n}=C_{m\times n}$ \
$ \left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right] + 
\left[
\begin{matrix}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\ 
b_{31} & b_{32} & b_{33} 
\end{matrix} 
\right] =
\left[
\begin{matrix}
a_{11}+b_{11} & a_{12}+b_{12} & a_{13}+b_{13} \\
a_{21}+b_{21} & a_{22}+b_{22} & a_{23}+b_{23} \\ 
a_{31}+b_{31} & a_{32}+b_{32} & a_{33}+b_{33} 
\end{matrix} 
\right]$

Operasi penjumlahan matriks ini masih memiliki sifat komutatif ($A+B=B+A$). Sedangkan operasi pengurangan berlaku sifat $A-B=-B+A$.

Contoh :

Latihan soal :
1. (di papan aja deh)
1. 
1. 


Some Markdown text with 
<span style="background-color:yellow;">some **yellow highlight** text</span>.


### Operasi perkalian dengan skalar

Misal terdapat bilangan/skalar $k$ dan matriks $A$ (dengan ordo bebas), maka perkalian skalar terhadap matriks $A$ atau $k.A$ adalah perkalian setiap elemen dari matriks $A$ dengan skalar $k$

Operasi perkalian skalar dinotasikan sebagai berikut :
> $k.A=k. \left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{matrix} 
\right] = \left[
\begin{matrix}
k.a_{11} & k.a_{12} & k.a_{13} \\
k.a_{21} & k.a_{22} & k.a_{23} \\ 
k.a_{31} & k.a_{32} & k.a_{33} 
\end{matrix} 
\right]$

Operasi Perkalian skalar berlaku sifat berikut :

- $kA=Ak$
- $(k+m)A=kA+mA$
- $k(A+B)=kA+kB$
- $k(mA)=(km)A$

Contoh :

Latihan soal :
1. (di papan juga deh)
1. 
1. 

### Operasi perkalian dua matriks

Misal terdapat matriks $A$ dan $B$, keduanya dapat dikalikan jika banyaknya kolom pada matriks $A$ sama dengan banyaknya baris pada matriks $B$. Ordo kedua matriks yang dapat dikalikan adalah $A_{k \times l}$ dan $B_{l \times m}$. Operasi matriks ini *Unik*, karena **bukan** mengalikan setiap elemen yang seletak, tetapi **mengalikan setiap baris $A$ dengan setiap kolom $B$**

Operasi perkalian matriks dinotasikan sebagai berikut:
>$A_{k \times l} . B_{l \times m} = C_{k \times m}$ \
$ \left[
\begin{matrix}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{matrix} 
\right] . 
\left[
\begin{matrix}
b_{11} & b_{12} \\
b_{21} & b_{22} 
\end{matrix} 
\right] =
\left[
\begin{matrix}
a_{11}.b_{11}+a_{12}.b_{21} & a_{11}.b_{12}+a_{12}.b_{22} \\
a_{21}.b_{11}+a_{22}.b_{21} & a_{21}.b_{12}+a_{22}.b_{22} 
\end{matrix} 
\right]$

![alt perkalian_matriks](https://awsimages.detik.net.id/community/media/visual/2022/12/28/perkalian-matriks.jpeg?w=627)

Operasi perkalian matriks ini memiliki beberapa sifat :

- **TIDAK** selalu komutatif, \
    $A.B\ne B.A$
- Asosiatif, \
    $(A.B).C=A.(B.C)$
- Distributif, \
    $A.(B+C)=A.B+A.C$ (distributif kiri)\
    atau $(B+C).D=B.D+C.D$ (distributif kanan)
- Transpose \
    $(AB)^T=B^T.A^T$
- Perkalian skalar, \
    $c(AB)=(c.A)B=A(c.B)$
- Identitas \
    $A.I=I.A=A$
- Nol \
    $A.O=O.A=O$


Contoh :

Latihan soal :
1. (yaudah di papan)
1. 
1. 



Video menarik
[Link](https://youtu.be/ouP9xNujkNo?si=OelZhxVngxZhrQN-)

# Determinan

Determinan matriks adalah nilai skalar yang didapatkan dari perhitungan setiap elemen-elemen matriks persegi. Jadi matriks yang dapat ditentukan determinannya hanyalah matriks persegi.

Misal : \
$A=\left[
\begin{matrix}
a & b \\
c & d 
\end{matrix} 
\right] $

Determinan matriks $A_{2 \times 2}$ dinotasikan seperti berikut :
> $det(A)=|A|= \left|
\begin{matrix}
a & b \\
c & d 
\end{matrix} 
\right| = ad-bc$

Determinan matriks memiliki sifat berikut :
- $det(AB)=det(A)det(B)$
- $det(k.A)=k^n.det(A)$, dimana k skalar dan n adalah ordo dari $A$
- $det(A^T)=det(A)$
- $det(A^m)=(det(A))^m$
- $det(I)=1$
- $det(O)=0$
- $det(A^{-1})=\frac{1}{det(A)}$
- determinan matriks **segitiga/diagonal** adalah **perkalian seluruh diagonal utama**
- jika terdapat minimal dua baris ataupun dua kolom yang saling berkelipatan maka determinannya adalah 0
- determinan dari matriks yang salah satu baris/kolom **bernilai 0 semua** adalah 0

NB: \
Matriks yang memiliki **determinan 0** disebut sebagai matriks **singular**. Kebalikan darinya (yang memiliki determinan tidak nol) disebut matriks **asingular** atau **non-singular**

Latihan soal:
1. Tentukan determinan dari: \
    a. $A=\left[
\begin{matrix}
1 & 2 \\
0 & -3 
\end{matrix} 
\right], $ 
$|A|=-3$

    b. $B=\left[
\begin{matrix}
-2 & 2 \\
2 & 3 
\end{matrix} 
\right],$ 
$ |B|=-10$

    c. $C=\left[
\begin{matrix}
5 & -7 \\
3 & 3 
\end{matrix} 
\right],$
$ |C|=36$ 

    d. $K=\left[
\begin{matrix}
-3 & 4 \\
-1 & -2 
\end{matrix} 
\right],$ 
$|K|=10$ 

    e. $L=\left[
\begin{matrix}
7 & -6 \\
-2 & 2 
\end{matrix} 
\right],$
$ |L|=2$

    f. $M=\left[
\begin{matrix}
6 & 5 \\
5 & -4 
\end{matrix} 
\right],$ 
$ |M|=-49$ 

1. Tentukan determinan berikut menggunakan sifat determinan \
    a. $A.(3B)$ \
    b. $K.M^{-1}.(\frac{1}{2}C)$ \
    c. $L^2$ \
    d. $B^{-3}$ \
    e. $A^T.(2M)^2$ \
    f. $(C^{-1})^T.B^2.(2A)^{-1}$ 

## Metode Sarrus

Semua matriks persegi dapat dicari determinannya. Cara menentukan determinan untuk ordo lebih dari $2 \times 2$ bermacam-macam. Ada beberapa cara untuk menentukan determinan ordo tinggi, salah satunya adalah metode Sarrus. Metode Sarrus **mengalikan setiap diagonal utama (diberi tanda $+$) kemudian mengalikan setiap diagonal samping (diberi tanda $-$)**.

Determinan matriks $A_{3 \times 3}$ dengan Sarrus dinotasikan seperti berikut :
> $det(A)=|A|= \left|
\begin{matrix}
a & b & c\\
d & e & f\\
g & h & i
\end{matrix} 
\right| = 
\left|
\begin{matrix}
a & b & c\\
d & e & f\\
g & h & i
\end{matrix}
\right| 
\begin{matrix}
a & b\\
d & e\\
g & h
\end{matrix}$ \
$=(aei+bfg+cdh)-(ceg+afh+bdi)$

![alt sarrus](https://penma2b.files.wordpress.com/2016/08/det_a_copy.png)

![alt sarrus2](https://1.bp.blogspot.com/-3HW0pLjY-Gc/YTjDf_aODbI/AAAAAAAAGwY/slouDCMMPIY8Fcn96bNDpwYfNQZzXQ6ZwCLcBGAsYHQ/s316/gambar%2Bsoal%2B145.PNG)

Contoh soal:
1. $A= 
\left[
\begin{matrix}
1 & 2 & -3\\
-4 & 5 & 6\\
7 & -8 & 9
\end{matrix}
\right] $ \
$det(A)=|A|= \left|
\begin{matrix}
1 & 2 & -3\\
-4 & 5 & 6\\
7 & -8 & 9
\end{matrix} 
\right| = 
\left|
\begin{matrix}
1 & 2 & -3\\
-4 & 5 & 6\\
7 & -8 & 9
\end{matrix}
\right| 
\begin{matrix}
1 & 2\\
-4 & 5\\
7 & -8
\end{matrix}$ \
$=(1.5.9+2.6.7+(-3)(-4)(-8))-((-3)5.7+1.6(-8)+2(-4)9)$ \
$=(45+84-96)-(-105-48-72)$ \
$=33-(-225)$ \
$=33+225$ \
$=258$


Latihan Soal
1. $A= 
\left[
\begin{matrix}
1 & 3 & 3\\
2 & 1 & 4\\
3 & 1 & 2
\end{matrix}
\right] $
1. $B= 
\left[
\begin{matrix}
3 & 2 & 3\\
5 & 4 & 1\\
1 & 2 & 3
\end{matrix}
\right] $
1. $C= 
\left[
\begin{matrix}
-1 & 3 & 2\\
0 & 2 & -3\\
4 & 0 & 1
\end{matrix}
\right] $
1. $K= 
\left[
\begin{matrix}
-1 & 1 & 2\\
3 & 1 & -4\\
2 & -2 & 4
\end{matrix}
\right] $
1. $L= 
\left[
\begin{matrix}
6 & 2 & 0\\
-4 & -2 & 0\\
3 & 1 & 0
\end{matrix}
\right] $
1. $M= 
\left[
\begin{matrix}
-1 & 1 & 2\\
7 & 1 & -8\\
2 & -2 & -4
\end{matrix}
\right] $

## Metode Minor-Kofaktor

Metode Minor-Kofaktor menerapkan operasi dengan m**engubah ukuran matriks menjadi lebih kecil**. Misalkan matriks persegi dengan ordo 3 akan disederhanakan menjadi ordo 2, matriks persegi dengan ordo 4 akan di sederhanakan menjadi ordo 3, dan seterusnya. Metode ini adalah salah satu cara untuk menentukan determinan dan invers suatu matriks dengan ordo yang lebih tinggi.

Notasi minor matriks:
> $M_{ij}$ adalah sub (bagian) dari matriks yang **seluruh baris ke $i$ dan seluruh baris ke $j$ tidak dicoret**, contoh: \
$M_{11}=\left[
\begin{matrix}
a_{22} & a_{23} \\
a_{32} & a_{33} 
\end{matrix} 
\right]$ \
$|M_{23}|=\left|
\begin{matrix}
a_{11} & a_{12} \\
a_{31} & a_{32} 
\end{matrix} 
\right| = a_{11}a_{32}-a_{12}a_{31}$

![alt minor](https://yunilestari869.files.wordpress.com/2016/11/3fd63-minor_matriks.png)

**Matriks kofaktor** dari $A$ dilambangkan sebagai $C$, yang elemen-elemennya adalah $c_{ij}$. \
Notasi dari kofaktor :
> $c_{ij}=(-1)^{i+j}.\left| M_{ij}\right|=(-1)^{i+j}.det M_{ij}$ \
$C=
\left[
\begin{matrix}
\left| M_{11}\right| & -\left| M_{12}\right| & \left| M_{13}\right| \\
-\left| M_{21}\right| & \left| M_{22}\right| & -\left| M_{23}\right| \\
\left| M_{31}\right| & -\left| M_{32}\right| & \left| M_{33}\right|
\end{matrix}
\right]$


Determinan $A_{n\times n}$ dapat dicari dengan menerapkan metode kofaktor pada **salah satu baris** atau **salah satu kolom matriks** $A$. Penerapan kofaktor untuk determinan seperti berikut:
> $det(A)=\sum_{i=1}^{n} a_{il}.c_{il}$ **atau** \
$det(A)=\sum_{j=1}^{n} a_{kj}.c_{kj}$ \
dimana $l$ adalah salah satu kolom dan $k$ adalah salah satu baris


Contoh untuk $A_{3\times 3}$ (menggunakan kofaktor baris pertama): \
$det(A)= a_{11}.c_{11}+a_{12}.c_{12}+a_{13}.c_{13}$ \
$det(A)= a_{11}.(-1)^{1+1}.\left| M_{11}\right|
+a_{12}.(-1)^{1+2}.\left| M_{12}\right|
+a_{13}.(-1)^{1+3}.\left| M_{13}\right|$ \
$det(A)= a_{11}.\left| M_{11}\right|
-a_{12}.\left| M_{12}\right|
+a_{13}.\left| M_{13}\right|$ \
$det(A)= a_{11}.\left| 
\begin{matrix}
a_{22} & a_{23} \\
a_{32} & a_{33} 
\end{matrix} 
\right|
-a_{12}.\left| 
\begin{matrix}
a_{21} & a_{23} \\
a_{31} & a_{33} 
\end{matrix} 
\right|
+a_{13}.\left| 
\begin{matrix}
a_{21} & a_{22} \\
a_{31} & a_{32} 
\end{matrix} 
\right|$

## Adjoin Matriks

Adjoin dari suatu matriks digunakan untuk mencari invers suatu matriks.
Secara umum notasi Adjoin sebagai berikut:
> $Adj(A)=C^T$ \
atau untuk matriks dengan ordo $2 \times 2$. $ A_{2 \times 2}=
\left[
\begin{matrix}
a & b \\
c & d 
\end{matrix} 
\right]$ \
$Adj(A_{2 \times 2})=\left[ 
\begin{matrix}
d & -b \\
-c & a  
\end{matrix} 
\right]$

# Invers Matriks

Invers matriks adalah matriks yang didapatkan dari kebalikan matriks asal. Misalkan terdapat dua buah matriks, yaitu $A$ dan $B$. Jika memenuhi $AB=BA=I$, maka $B$ adalah invers dari matriks $A$.

Invers matriks dinotasikan sebagai:
> $A^{-1}=\frac{1}{det(A)}.Adj(A)$

Invers matriks denga ordo $2 \times 2$ ditentukan dengan :
> Jika $A=\left[ 
\begin{matrix}
a & b \\
c & d  
\end{matrix} 
\right]$ \
maka $A^{-1}=\frac{1}{ad-bc}.\left[ 
\begin{matrix}
d & -b \\
-c & a  
\end{matrix} 
\right]$

Invers matriks memiliki sifat berikut:
- $A.A^{-1}=A^{-1}.A=I$
- $A.I=I.A=A$
- $(A.B)^{-1}=B^{-1}.A^{-1}$
- $A^{-n}=(A^{-1})^n=(A^n)^{-1}$
- $(A^{-1})^{-1}=A$
- $(A^T)^{-1}=(A^{-1})^T$
- $(k.A)^{-1}= \frac{1}{k} .A^{-1}$
- $det(A^{-1})=\frac{1}{det(A)}$
- $AX=B$ maka $X=A^{-1}B$
- $XA=B$ maka $X=BA^{-1}$
- Matriks *singular* tidak memiliki invers

 Contoh :
 1. $A=\left[ 
\begin{matrix}
1 & -2 \\
3 & -5  
\end{matrix} 
\right]$ \
maka $A^{-1}=\frac{1}{1.(-5)-(-2).3}.\left[ 
\begin{matrix}
-5 & -(-2) \\
-3 & 1  
\end{matrix} 
\right]$ \
$A^{-1}=\frac{1}{-5+6}.\left[ 
\begin{matrix}
-5 & 2 \\
-3 & 1  
\end{matrix} 
\right]$ \
$A^{-1}=\frac{1}{1}.\left[ 
\begin{matrix}
-5 & 2 \\
-3 & 1  
\end{matrix} 
\right]$ \
$A^{-1}=\left[ 
\begin{matrix}
-5 & 2 \\
-3 & 1  
\end{matrix} 
\right]$


Latihan Soal :
Tentukan determinan, adjoin, dan invers dari matriks berikut
1. $A=\left[ 
\begin{matrix}
3 & 7 \\
-2 & -5  
\end{matrix} 
\right]$ 
1. $B=\left[ 
\begin{matrix}
-3 & 5 \\
4 & -7  
\end{matrix} 
\right]$ 
1. $C=\left[ 
\begin{matrix}
4 & -13 \\
-2 & 6  
\end{matrix} 
\right]$ 
1. $K=\left[ 
\begin{matrix}
9 & 5 \\
-6 & -3  
\end{matrix} 
\right]$ 
1. $L=\left[ 
\begin{matrix}
3 & -4 \\
-2 & -6  
\end{matrix} 
\right]$ 
1. Tentukan $(A.B)^{-1}$
1. Tentukan $(B)^{-2}$
1. Tentukan $(\frac{1}{2}.K)^{-1}$

In [29]:
import numpy as np
n = 10
dim = 2
k = 0
while k<n:
    m = np.random.choice(list(np.arange(21)-10), dim**2).reshape((dim,dim))
    d = np.linalg.det(m)
    if d!=0 :
        inv = np.linalg.inv(m)
        if (np.mod(inv,0.01)<0.0001).all():
            k +=1
            print(k, m, '\ndet  = ', np.round(d), '\n invers =\n',inv, '\n')

1 [[ 2 -1]
 [-6  4]] 
det  =  2.0 
 invers =
 [[2.  0.5]
 [3.  1. ]] 

2 [[ 3 -2]
 [-2  0]] 
det  =  -4.0 
 invers =
 [[ 0.   -0.5 ]
 [-0.5  -0.75]] 

3 [[ 1 -6]
 [-9  4]] 
det  =  -50.0 
 invers =
 [[-0.08 -0.12]
 [-0.18 -0.02]] 

4 [[ -4 -10]
 [  3  10]] 
det  =  -10.0 
 invers =
 [[-1.  -1. ]
 [ 0.3  0.4]] 

5 [[ 2 -3]
 [-1  1]] 
det  =  -1.0 
 invers =
 [[-1. -3.]
 [-1. -2.]] 

6 [[-10   3]
 [ 10   2]] 
det  =  -50.0 
 invers =
 [[-0.04  0.06]
 [ 0.2   0.2 ]] 

7 [[-8 10]
 [ 3 -4]] 
det  =  2.0 
 invers =
 [[-2.  -5. ]
 [-1.5 -4. ]] 

8 [[ 9 -1]
 [-2  0]] 
det  =  -2.0 
 invers =
 [[ 0.  -0.5]
 [-1.  -4.5]] 

9 [[-1  1]
 [ 2 -6]] 
det  =  4.0 
 invers =
 [[-1.5  -0.25]
 [-0.5  -0.25]] 

10 [[-6  1]
 [ 4 -4]] 
det  =  20.0 
 invers =
 [[-0.2  -0.05]
 [-0.2  -0.3 ]] 



# Aplikasi Matriks

Matriks memiliki ribuan aplikasi, khususnya pada bidang teknologi canggih, astronomi, kecerdasan buatan, penjadwalan kereta dan lain sebagainya. Matriks dimanfaatkan untuk menyederhanakan proses perhitungan matematika yang membutuhkan solusi dari persamaan dengan variabel yang banyak seperti sistem persamaan linear. tidak hanya SPLDV, matriks dapat menyelesaikan SPLTV atau SPL yang memiliki variabel yang lebih tinggi lagi seperti 4 variabel, 5, 6, dan sebagainya jika kita dapat menentukan determinannya.

Ada beberapa metode dalam penyelesaian sistem persamaan linear dengan matriks, salah satunya :
- Metode Invers
- Metode Cramer
- Metode Eliminasi Gauss
- Metode Eliminasi Gauss Jordan

## Penyelesaian SPL dengan Metode Invers

Jika terdapat suatu permasalahan SPLDV, misal: \
$ax+by=p$ \
$cx+dy=q$ \
ubah dahulu dalam bentuk matriks seperti berikut : \
$\left[
\begin{matrix}
a & b \\
c & d
\end{matrix}
\right]
\left[
\begin{matrix}
x \\
y
\end{matrix}
\right] =
\left[
\begin{matrix}
p \\
q
\end{matrix}
\right]$

Notasi metode invers untuk matriks $2 \times 2$ :
> $\left[
\begin{matrix}
x \\
y
\end{matrix}
\right] =
\left[
\begin{matrix}
a & b \\
c & d
\end{matrix}
\right] ^{-1}
\left[
\begin{matrix}
p \\
q
\end{matrix}
\right]$ \
$\left[
\begin{matrix}
x \\
y
\end{matrix}
\right] = \frac{1}{ad-bc}
\left[
\begin{matrix}
d & -b \\
-c & a
\end{matrix}
\right]
\left[
\begin{matrix}
p \\
q
\end{matrix}
\right]$

Contoh :
1. Selesaikan SPLDV berikut, 


Latihan Soal :
1. Selesaikan sistem persamaan linear dua variabel berikut dengan invers matriks \
    a. x+y=13, x-y=-11 \
    b. \
    c. \
    d. (selanjutnya di program)

## Penyelesaian SPL dengan  Metode Cramer

### Penyelesaian SPLDV
Jika terdapat suatu permasalahan SPLDV, misal: \
$ax+by=p$ \
$cx+dy=q$ \
ubah dahulu dalam bentuk matriks seperti berikut : \
$\left[
\begin{matrix}
a & b \\
c & d
\end{matrix}
\right]
\left[
\begin{matrix}
x \\
y
\end{matrix}
\right] =
\left[
\begin{matrix}
p \\
q
\end{matrix}
\right]
$

Notasi metode cramer untuk matriks $2 \times 2$ :
> $x=\frac{D_x}{D}$ \
$y=\frac{D_y}{D}$

dimana : \
$D=\left|
\begin{matrix}
a & b \\
c & d
\end{matrix}
\right|$ \
$D_x=\left|
\begin{matrix}
p & b \\
q & d
\end{matrix}
\right|$ \
$D_y=\left|
\begin{matrix}
a & p \\
c & q
\end{matrix}
\right|$


### Penyelesaian SPLTV
Jika terdapat suatu permasalahan SPLTV, misal: \
$ax+by+cz=k$ \
$dx+ey+fz=l$ \
$gx+fy+iz=m$ \
ubah dahulu dalam bentuk matriks seperti berikut : \
$\left[
\begin{matrix}
a & b & c \\
d & e & f \\
g & h & i
\end{matrix}
\right]
\left[
\begin{matrix}
x \\
y \\
z
\end{matrix}
\right] =
\left[
\begin{matrix}
k \\
l \\
m
\end{matrix}
\right]
$

Notasi metode cramer untuk matriks $3 \times 3$ :
> $x=\frac{D_x}{D}$ \
$y=\frac{D_y}{D}$ \
$z=\frac{D_z}{D}$

dimana : \
$D=\left|
\begin{matrix}
a & b & c \\
d & e & f \\
g & h & i
\end{matrix}
\right|$ \
$D_x=\left|
\begin{matrix}
k & b & c \\
l & e & f \\
m & h & i
\end{matrix}
\right|$ \
$D_y=\left|
\begin{matrix}
a & k & c \\
d & l & f \\
g & m & i
\end{matrix}
\right|$ \
$D_z=\left|
\begin{matrix}
a & b & k \\
d & e & l \\
g & h & m
\end{matrix}
\right|$